
import colorama
colorama.init(autoreset=True)

GREEN = colorama.Fore.GREEN
LIGHT_GREEN = colorama.Fore.LIGHTGREEN_EX

BLUE = colorama.Fore.BLUE
SKY_BLUE = colorama.Fore.LIGHTBLUE_EX
CYAN = colorama.Fore.CYAN
BABY_BLUE = colorama.Fore.LIGHTCYAN_EX

RED = colorama.Fore.RED
BRIGHT_RED = colorama.Fore.LIGHTRED_EX

YELLOW = colorama.Fore.YELLOW
BRIGHT_YELLOW = colorama.Fore.LIGHTYELLOW_EX

PURPLE = colorama.Fore.MAGENTA
PINK = colorama.Fore.LIGHTMAGENTA_EX

WHITE = colorama.Fore.WHITE
BRIGHT_WHITE = colorama.Fore.LIGHTWHITE_EX

BLACK = colorama.Fore.BLACK
GRAY = colorama.Fore.LIGHTBLACK_EX

#* COLORS
NAME_COLOR = LIGHT_GREEN
HEAL_COLOR = LIGHT_GREEN
WEAPON_COLOR = GRAY
INFO_COLOR = GREEN
CRITICAL_COLOR = GREEN
POISON_COLOR = PURPLE
BURN_COLOR = RED
PARALYSIS_COLOR = YELLOW
CONFUSE_COLOR = PINK
FREEZE_COLOR = CYAN
DAMAGE_COLOR = WHITE
INCREASE_COLOR = BRIGHT_YELLOW
DECREASE_COLOR = BRIGHT_RED
DODGE_COLOR = GRAY
MISS_COLOR = BRIGHT_RED
BLIND_COLOR = GRAY
ERROR_COLOR = RED
ENERGY_COLOR = PURPLE
NO_OPTION_COLOR = GRAY

TAB:str = ' ' * 40
HEALTH_BARS:int = 20

NORMAL_DELAY_TIME:float = 0.05
END_DELAY_TIME:float = 1.0
SKIP_DELAY_TIME:float = 0.5

STAT_MAX:int = 150
STAT_MIN:int = 100

STARTING_CRITICAL_CHANCE = 25
STARTING_CRITICAL_POWER = 1.25

LEVEL_DIVIDER = 200

POISON_DAMAGE_PERCENT = 0.15

BURN_ATTACK_PERCENT = 0.125
BURN_HEALTH_PERCENT = 0.125
BURN_CHANCE = 3

PARALYSIS_CHANCE = 2

CONFUSE_DEFENSE_PERCENT = 0.25
CONFUSE_CHANCE = 3

FREEZE_SPEED_PERCENT = 0.25
FREEZE_CHANCE = 3

REST_ENERGY = 0.50

DELETE_CHARACTERS = 1000

LOOP_MAP_NUMBER = 20 # Bigger = Slower


INPUT_DELAY = 0.1